export class JasonDOM{
    private static textBoxTemplateElement:HTMLTemplateElement;
    static initializeTemplateElements(){
        JasonDOM.textboxTemplate();
    }
    static textboxTemplate():HTMLTemplateElement{
        if(!JasonDOM.textBoxTemplateElement) {
            let templateString = `
            <input type="text" class="${JasonDOM.classes.JW_TEXT_BOX}"
                data-bind-sbf="attr:{readonly:options.readonly,enabled:options.enabled,placeholder:options.placeholder};visible:options.visible;value:value"
            />
        `;
            JasonDOM.textBoxTemplateElement = document.createElement("template");
            JasonDOM.textBoxTemplateElement.setAttribute("id",JasonDOM.templates.JW_TEXTBOX_TEMPLATE);
            JasonDOM.textBoxTemplateElement.innerHTML = templateString;
            document.body.appendChild(JasonDOM.textBoxTemplateElement);
        }
        return JasonDOM.textBoxTemplateElement;
    }
    static templates = {
        JW_TEXTBOX_TEMPLATE:"jasonTextboxTemplate"
    }
    static JW_ICON = "jw-icon fa fa-fw "
    static classes ={
        grids:{
            GRID: "jw-grid-non-tabular",
            GRID_HEADER: "jw-grid-header",
            GRID_BODY: "jw-grid-body",
            GRID_FOOTER:"jw-grid-footer",
            GRID_COLUMN: "jw-grid-column",
            GRID_COLUMN_CAPTION: "jw-grid-column-caption",
            GRID_COLUMN_BUTTON: "jw-grid-column-button",
            GRID_FILTER:"jw-grid-filter",
            GRID_GROUPING_CONTAINER: "jw-grid-grouping",
            GRID_GROUPING_MESSAGE: "jw-grouping-message"
        },
        JW_BASECLASS:"jasonWidget",
        JW_BUTTON: "jw-button",
        JW_BUTTON_STANDALONE:"standalone",
        JW_BUTTON_ELEMENT: "jw-button-element",
        JW_BLOCK_ELEMENT: "jw-block-element",
        JW_CALENDAR : "jw-calendar",
        JW_CALENDAR_BODY : "jw-calendar-body",
        JW_CALENDAR_DISPLAY : "jw-calendar-display",
        JW_CALENDAR_FOOTER : "jw-calendar-footer",
        JW_CALENDAR_GO_BACK : "jw-calendar-back",
        JW_CALENDAR_GO_FORWARD : "jw-calendar-forward",
        JW_CALENDAR_HEADER : "jw-calendar-header",
        JW_CALENDAR_ITEM_OUT_CURRENT_SCOPE: "jw-calendar-item-outofscope",
        JW_CALENDAR_ITEM_SELECTED_DATE : "selected-date",
        JW_CALENDAR_JW_TABLE_CENTURIES : "centuries-view",
        JW_CALENDAR_JW_TABLE_DECADES : "decades-view",
        JW_CALENDAR_JW_TABLE_MONTHS : "month-view",
        JW_CALENDAR_JW_TABLE_YEARS: "years-view",
        JW_CHECKBOX_INPUT : "jw-checkbox",
        JW_CLEAR_FLOAT_CLASS: "jw-clear-float",
        JW_BORDERED : "jw-bordered",
        JW_BUTTON_TEXT_BOX : "jw-button-textbox",
        JW_COMBOBOX_CLASS : "jw-combobox",
        JW_DATE_PICKER_CLASS: "jw-date-picker",
        JW_DIALOG_BODY   : "jw-dialog-body",
        JW_DIALOG_BUTTONS_CONTAINER: "jw-dialog-buttons",
        JW_DIALOG_CONTAINER : "jw-dialog-container",
        JW_DIALOG_FOOTER : "jw-dialog-footer",
        JW_DIALOG_HEADER: "jw-dialog-header",
        JW_DIALOG_TITLE_CONTAINER: "title-container",
        JW_DIALOG_HEADER_BUTTON_CONTAINER:"header-button-container",
        JW_DISABLED : "jw-disabled",
        JW_DRAG_IMAGE: "jw-drag-image-container",
        JW_DROP_DOWN_LIST: "jw-drop-down-list",
        JW_DROP_DOWN_LIST_ITEM: "drop-down-list-item",
        JW_DROP_DOWN_BUTTON_MULTI_SELECT:"jw-drop-down-button-multi-select",
        JW_FOCUSED:"jw-focused",
        JW_GRID_CLASS : "jw-grid",
        JW_GRID_COLUMN_DRAG_IMAGE : "jw-grid-column-drag-image",
        JW_GRID_COLUMN_RESIZE_HANDLE : "jw-column-resize",
        JW_GRID_DATA : "jw-grid-data",
        JW_GRID_DATA_CONTAINER : "jw-grid-data-container",
        JW_GRID_FIELD_HAS_FILTER : "jw-grid-column-has-filter",
        JW_GRID_FILTER_ACTION_BUTTON_CLASS: "jw-grid-filter-action-button",
        JW_GRID_FILTER_BODY_CLASS : "jw-grid-filter-body",
        JW_GRID_FILTER_CONTAINER_CLASS : "jw-grid-filter-container",
        JW_GRID_FILTER_FOOTER_CLASS : "jw-grid-filter-footer",
        JW_GRID_FILTER_HEADER_CLASS : "jw-grid-filter-header",
        JW_GRID_FILTER_INPUT : "jw-filter-input",
        JW_GRID_FOCUSED_CELL_CLASS : "cell-focused",
        JW_GRID_FOOTER : "jw-grid-footer",
        JW_GRID_FOOTER_CONTAINER : "jw-grid-footer-container",
        JW_GRID_GROUPING_CONTAINER_CLASS : "jw-grid-group-container",
        JW_GRID_GROUP_CELL: "group-cell",
        JW_GRID_GROUP_KEY_CAPTION:"group-key-caption",
        JW_GRID_GROUPING_MESSAGE:"jw-grouping-message",
        JW_GRID_HEADER : "jw-grid-header",
        JW_GRID_HEADER_CELL_CAPTION_CONTAINER : "jw-header-cell-caption",
        JW_GRID_HEADER_CELL_ICON_CONTAINER : "jw-header-cell-icon",
        JW_GRID_HEADER_CONTAINER : "jw-grid-header-container",
        JW_GRID_HEADER_CONTAINER_NO_GROUPING : "no-grouping",
        JW_GRID_HEADER_JW_TABLE_CONTAINER: "jw-grid-header-table-container",
        JW_GRID_JW_TABLE_ALT_ROW_CLASS : "row-alt",
        JW_GRID_JW_TABLE_CELL_CLASS : "jw-grid-cell",
        JW_GRID_JW_TABLE_CELL_CONTENT_CONTAINER_CLASS : "jw-grid-cell-content",
        JW_GRID_JW_TABLE_GROUP_ROW_CLASS : "group-row",
        JW_GRID_JW_TABLE_NO_DATA_ROW_CLASS: "jw-grid-no-data-row",
        JW_GRID_JW_TABLE_ROW_CLASS : "jw-grid-row",
        JW_GRID_SELECTED_CELL_CLASS : "cell-selected",
        JW_GRID_SELECTED_ROW_CLASS: "row-selected",
        JW_GRID_REMOVE_GROUP_BUTTON: "jw-grid-remove-grouping",
        JW_GRID_UNSELECTABLE:"unselectable",
        JW_HAS_ARROW: "has-arrow",
        JW_HAS_CHECKBOX: "has-checkbox",
        JW_HAS_ICON: "has-icon",
        JW_JW_GRID_FILTER_BUTTON_APPLY : "apply-filter",
        JW_JW_GRID_FILTER_BUTTON_CLEAR : "clear-filter",
        JW_LABEL: "jw-label",
        JW_INVALID :"jw-invalid",
        JW_MENU_CLASS : "jw-menu",
        JW_MENU_CONTAINER_CLASS : "jw-menu-container",
        JW_MENU_HORIZONTAL: "horizontal",
        JW_MENU_VERTICAL: "vertical",
        JW_MENU_ITEM : "jw-menu-item",
        JW_MENU_ITEMS_CONTAINER_CLASS : "jw-menu-items-container",
        JW_MENU_ITEM_ARROW : "jw-menu-item-arrow",
        JW_MENU_ITEM_CAPTION : "jw-menu-item-caption",
        JW_MENU_ITEM_CAPTION_ONLY : "just-caption",
        JW_MENU_ITEM_CHECKBOX : "jw-menu-item-checkbox",
        JW_MENU_ITEM_CHECKBOX_CLASS : "jw-menu-item-checkbox",
        JW_MENU_ITEM_CLASS : "jw-menu-item",
        JW_MENU_ITEM_CLASS_ACTIVE: "jw-menu-item-active",
        JW_MENU_ITEM_CLICKABLE : "clickable",
        JW_MENU_ITEM_CONTENT : "menu-content",
        JW_MENU_ITEM_CONTENT_CLASS : "jw-menu-item-content",
        JW_MENU_ITEM_DISABLED : "disabled",
        JW_MENU_ITEM_DIVIDER : "divider",
        JW_MENU_ITEM_ICON: "jw-menu-item-icon",
        JW_NUMERIC_TEXT_BOX: "jw-numeric-textbox",
        JW_PAGER_CONTAINER_CLASS : "jw-grid-pager",
        JW_PAGER_CONTAINER_PAGE_INFO_CLASS: "jw-grid-pager-info",
        JW_POPOVER: "jw-popover",
        JW_POPOVER_HEADER: "jw-popover-header",
        JW_POPOVER_BODY: "jw-popover-body",
        JW_READONLY: "jw-readonly",
        JW_SELECTED: "jw-selected",
        JW_TAB_CONTAINER : "jw-tabcontrol-container",
        JW_TAB_PAGE_ACTIVE: 'jw-tab-active',
        JW_TAB_PAGE_CLASS : "jw-tabcontrol-page",
        JW_TAB_PAGE_CONTAINER : "jw-tabcontrol-page-container",
        JW_TAB_PAGE_CONTENT_CONTAINER_CLASS : "jw-tabcontrol-page-container",
        JW_TAB_UL_CLASS: "jw-tabcontrol-list",
        JW_TEXT_BOX: "jw-textbox",
        JW_TEXT_INPUT : "jw-text-input",
        JW_TEXT_OVERFLOW: "jw-text-overflow",
        JW_TOP: "top",
        JW_BOTTOM: "bottom",
        JW_LEFT: "left",
        JW_RIGHT: "right",
        JW_MIDDLE: "middle",
        JW_ARROW_LEFT: "arrow-left",
        JW_ARROW_RIGHT: "arrow-right",
        JW_ARROW_MIDDLE: "arrow-middle",
        JW_UNSELECTABLE_TABLE: "jw-unselectable",
        JW_VALIDATION: "jw-validation-bubble",
        JW_VALIDATION_CONTAINER: "jw-validation-container",
        JW_VALIDATION_MESSAGE_CONTAINER: "jw-validation-message-container",
        JW_VALIDATION_MESSAGE: "jw-validation-message",
    }
    static attributes = {
        COLSPAN_ATTR: "colspan",
        DRAGGABLE_ATTR: "draggable",
        HREF_ATTR: "href",
        INPUT_MODE_ATTR: "inputmode",
        ID_ATTR: "id",
        FOR_ATTR: "for",
        DISABLED_ATTR: "disabled",
        DATA_FIELD:"data-field",
        JW_COMBOBOX_LIST_STATE_ATTR: "jw-drop-down-list-state",
        JW_DATA_CELL_ID_ATTR: "jw-data-cell-id",
        JW_DATA_GROUPING_FIELD_ATTR: "jw-data-grouping-field",
        JW_DATA_GROUPING_KEY_ATTR: "jw-data-group-key",
        JW_DATA_GROUPING_LEVEL_ATTR: "jw-data-grouping-level",
        JW_DATA_GROUP_COLLAPSED_ATTR: "jw-data-group-collpsed",
        JW_DATA_GROUP_EXPANDED_ATTR: "jw-data-group-expanded",
        JW_DATA_JW_ITEM_INDEX_ATTR: "jw-data-item-index",
        JW_DATA_ROW_ID_ATTR: "jw-data-row-id",
        JW_DIRECTION_ATTR: "jw-direction",
        JW_GRID_GROUP_FIELD: "jw-group-field",
        JW_GRID_COLUMN_ID_ATTR: "jw-column-id",
        JW_GRID_COLUMN_FIELD_ATTR: "jw-column-field",
        JW_GRID_COLUMN_SORT_ATTR: "jw-column-sort",
        JW_ITEM_INDEX_ATTR: "jw-item-index",
        JW_MENU_ITEM_LEVEL_ATTRIBUTE: "data-jason-menu-item-level",
        JW_MENU_ITEM_NO_HIGHLIGHT_ATTR: "no-highlight",
        PATTERN_ATTR : "pattern",
        PLACEHOLDER_ATTR: "placeholder",
        READONLY_ATTR: "readonly",
        TABINDEX_ATTR: "tabindex",
        TITLE_ATTR: "title",
        TYPE_ATTR: "type"
    }
    static attributeValues = {
        JW_COMBOBOX_LIST_STATE_DOWN: "down",
        JW_COMBOBOX_LIST_STATE_UP: "up",
        JW_DIALOG_BUTTON_DATA_KEY: "jasonDialogButton",
        JW_MENU_ITEM_DATA_KEY: "jasonMenuItem"
    }
    static icons = {
        CALENDAR: JasonDOM.JW_ICON + "fa-calendar",
        CHEVRON_DOWN: JasonDOM.JW_ICON + "fa-chevron-down",
        CHEVRON_UP: JasonDOM.JW_ICON + "fa-chevron-up",
        CHEVRON_LEFT: JasonDOM.JW_ICON + "fa-chevron-left",
        CHEVRON_RIGHT: JasonDOM.JW_ICON + "fa-chevron-right",
        CIRCLE_ARROW_DOWN: JasonDOM.JW_ICON + "fa-chevron-circle-down",
        CIRCLE_ARROW_UP: JasonDOM.JW_ICON + "fa-chevron-circle-up",
        CIRCLE_ARROW_LEFT: JasonDOM.JW_ICON + "fa-chevron-circle-left",
        CIRCLE_ARROW_RIGHT: JasonDOM.JW_ICON + "fa-chevron-circle-right",
        CIRCLE_CHOOSE: JasonDOM.JW_ICON + "fa-check-circle",
        CIRCLE_MINUS: JasonDOM.JW_ICON + "fa-minus-circle",
        CIRCLE_PLUS: JasonDOM.JW_ICON + "fa-plus-circle",
        CLOCK : JasonDOM.JW_ICON + "fa-clock-o",
        CLOSE: JasonDOM.JW_ICON + "fa-close",
        CLOSE_24x24: JasonDOM.JW_ICON + "fa-close",
        FILTER: JasonDOM.JW_ICON + "fa-filter",
        LIST: JasonDOM.JW_ICON + "fa-list",
        MINUS: JasonDOM.JW_ICON + "fa-minus",
        PLUS: JasonDOM.JW_ICON + "fa-plus",
        REMOVE_SORT: JasonDOM.JW_ICON + "fa-trash",
        REMOVE_FILTER: JasonDOM.JW_ICON + "fa-trash",
        SEARCH: JasonDOM.JW_ICON + "fa-search",
        SETTINGS : JasonDOM.JW_ICON + "fa-cog",
        SIGNAL: JasonDOM.JW_ICON + "fa-signal",
        SORT_ASC: JasonDOM.JW_ICON + "fa-sort-amount-asc",
        SORT_DESC: JasonDOM.JW_ICON + "fa-sort-amount-desc",
        CHEVRON_DOWN16x16: JasonDOM.JW_ICON + "fa-chevron-down",
        CHEVRON_UP16x16: JasonDOM.JW_ICON + "fa-chevron-up"
    }
}